---
- name: remove the target file
  file:
    state: absent
    path: "{{ jar_path }}"

- name: kill the process
  command: python "{{ script_name }}" stop
  args:
    chdir: /home/project/

- name: Download security jar file
  get_url:
     url: "{{ jar_url }}"
     dest: /home/project

- name: wait 20 seconds
  pause:
    seconds: 20

- name: start server again
  command: python "{{ script_name }}" start
  args:
    chdir: /home/project/

- name: wait for server to start
  wait_for: port="{{ server_port }}"

